"""clean_schema_usernames

Revision ID: 5de5ec764554
Revises: 8f201ed2010a
Create Date: 2026-05-08 21:04:02.362906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de5ec764554'
down_revision: Union[str, Sequence[str], None] = '8f201ed2010a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('p1_username', sa.String(length=32), server_default='', nullable=False))
    op.add_column('matches', sa.Column('p2_username', sa.String(length=32), server_default='', nullable=False))
    op.drop_column('matches', 'p1_rtt_ms')
    op.drop_column('matches', 'p2_rtt_ms')
    op.drop_column('rounds', 'p2_server_rt_ms')
    op.drop_column('rounds', 'p1_server_rt_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('p1_server_rt_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('rounds', sa.Column('p2_server_rt_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('p2_rtt_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('p1_rtt_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('matches', 'p2_username')
    op.drop_column('matches', 'p1_username')
    # ### end Alembic commands ###
