"""add_anticheat_behavioral_hardware_columns

Revision ID: 761ccac19331
Revises: faab73b73111
Create Date: 2026-05-09 01:43:45.715765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761ccac19331'
down_revision: Union[str, Sequence[str], None] = 'faab73b73111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('p1_platform', sa.String(length=16), nullable=True))
    op.add_column('matches', sa.Column('p2_platform', sa.String(length=16), nullable=True))
    op.add_column('matches', sa.Column('p1_screen_refresh_hz', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('p2_screen_refresh_hz', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('p1_screen_resolution', sa.String(length=16), nullable=True))
    op.add_column('matches', sa.Column('p2_screen_resolution', sa.String(length=16), nullable=True))
    op.add_column('matches', sa.Column('p1_client_version', sa.String(length=16), nullable=True))
    op.add_column('matches', sa.Column('p2_client_version', sa.String(length=16), nullable=True))
    op.add_column('rounds', sa.Column('p1_rtt_ms_round', sa.Float(), nullable=True))
    op.add_column('rounds', sa.Column('p2_rtt_ms_round', sa.Float(), nullable=True))
    op.add_column('rounds', sa.Column('p1_click_duration_ms', sa.Float(), nullable=True))
    op.add_column('rounds', sa.Column('p2_click_duration_ms', sa.Float(), nullable=True))
    op.add_column('rounds', sa.Column('p1_mouse_distance_5s_px', sa.Float(), nullable=True))
    op.add_column('rounds', sa.Column('p2_mouse_distance_5s_px', sa.Float(), nullable=True))
    op.add_column('rounds', sa.Column('p1_time_since_mouse_move_ms', sa.Float(), nullable=True))
    op.add_column('rounds', sa.Column('p2_time_since_mouse_move_ms', sa.Float(), nullable=True))
    op.add_column('rounds', sa.Column('p1_window_focused', sa.Boolean(), nullable=True))
    op.add_column('rounds', sa.Column('p2_window_focused', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'p2_window_focused')
    op.drop_column('rounds', 'p1_window_focused')
    op.drop_column('rounds', 'p2_time_since_mouse_move_ms')
    op.drop_column('rounds', 'p1_time_since_mouse_move_ms')
    op.drop_column('rounds', 'p2_mouse_distance_5s_px')
    op.drop_column('rounds', 'p1_mouse_distance_5s_px')
    op.drop_column('rounds', 'p2_click_duration_ms')
    op.drop_column('rounds', 'p1_click_duration_ms')
    op.drop_column('rounds', 'p2_rtt_ms_round')
    op.drop_column('rounds', 'p1_rtt_ms_round')
    op.drop_column('matches', 'p2_client_version')
    op.drop_column('matches', 'p1_client_version')
    op.drop_column('matches', 'p2_screen_resolution')
    op.drop_column('matches', 'p1_screen_resolution')
    op.drop_column('matches', 'p2_screen_refresh_hz')
    op.drop_column('matches', 'p1_screen_refresh_hz')
    op.drop_column('matches', 'p2_platform')
    op.drop_column('matches', 'p1_platform')
    # ### end Alembic commands ###
