"""add_latency_compensation_columns

Revision ID: 8f201ed2010a
Revises: b3e7f92a1c04
Create Date: 2026-05-08 18:54:02.051170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f201ed2010a'
down_revision: Union[str, Sequence[str], None] = 'b3e7f92a1c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('p1_server_rt_raw_ms', sa.Float(), nullable=True))
    op.add_column('rounds', sa.Column('p1_server_rt_compensated_ms', sa.Float(), nullable=True))
    op.add_column('rounds', sa.Column('p2_server_rt_raw_ms', sa.Float(), nullable=True))
    op.add_column('rounds', sa.Column('p2_server_rt_compensated_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'p2_server_rt_compensated_ms')
    op.drop_column('rounds', 'p2_server_rt_raw_ms')
    op.drop_column('rounds', 'p1_server_rt_compensated_ms')
    op.drop_column('rounds', 'p1_server_rt_raw_ms')
    # ### end Alembic commands ###
