"""initial schema

Revision ID: dd73f40c95ec
Revises: 
Create Date: 2026-05-06 17:36:25.117939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd73f40c95ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('matches_won', sa.Integer(), nullable=False),
    sa.Column('cheat_flag_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('p1_id', sa.String(length=16), nullable=False),
    sa.Column('p2_id', sa.String(length=16), nullable=False),
    sa.Column('winner_id', sa.String(length=16), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('room_code', sa.String(length=8), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('p1_final_score', sa.Integer(), nullable=False),
    sa.Column('p2_final_score', sa.Integer(), nullable=False),
    sa.Column('p1_rtt_ms', sa.Float(), nullable=True),
    sa.Column('p2_rtt_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['p1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['p2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=16), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('t_stimulus_us', sa.BigInteger(), nullable=False),
    sa.Column('delay_s', sa.Float(), nullable=False),
    sa.Column('p1_click_us', sa.BigInteger(), nullable=True),
    sa.Column('p2_click_us', sa.BigInteger(), nullable=True),
    sa.Column('p1_server_rt_ms', sa.Float(), nullable=True),
    sa.Column('p2_server_rt_ms', sa.Float(), nullable=True),
    sa.Column('p1_client_rt_ms', sa.Float(), nullable=True),
    sa.Column('p2_client_rt_ms', sa.Float(), nullable=True),
    sa.Column('winner_id', sa.String(length=16), nullable=True),
    sa.Column('p1_pre_click', sa.Boolean(), nullable=False),
    sa.Column('p2_pre_click', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rounds')
    op.drop_table('matches')
    op.drop_table('players')
    # ### end Alembic commands ###
