"""add_usernames_to_rounds_calibration

Revision ID: faab73b73111
Revises: 5de5ec764554
Create Date: 2026-05-08 21:13:53.822642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faab73b73111'
down_revision: Union[str, Sequence[str], None] = '5de5ec764554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibration_rounds', sa.Column('username', sa.String(length=32), server_default='', nullable=False))
    op.add_column('rounds', sa.Column('p1_username', sa.String(length=32), server_default='', nullable=False))
    op.add_column('rounds', sa.Column('p2_username', sa.String(length=32), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'p2_username')
    op.drop_column('rounds', 'p1_username')
    op.drop_column('calibration_rounds', 'username')
    # ### end Alembic commands ###
